"""empty message

Revision ID: 429a78059bfe
Revises: 9e1a12bc66b5
Create Date: 2020-06-28 18:43:04.031222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429a78059bfe'
down_revision = '9e1a12bc66b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###
