"""empty message

Revision ID: 547702446c4f
Revises: ba228f316fc4
Create Date: 2020-06-15 16:28:14.320923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547702446c4f'
down_revision = 'ba228f316fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_list', sa.Column('tasks', app.database.db_types.JsonCustomType.JsonCustomType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks_list', 'tasks')
    # ### end Alembic commands ###
