"""empty message

Revision ID: 9e1a12bc66b5
Revises: 6616a7df4681
Create Date: 2020-06-28 17:56:42.353372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1a12bc66b5'
down_revision = '6616a7df4681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###
